DROP TABLE IF EXISTS answer_citation CASCADE;
DROP TABLE IF EXISTS retrieval_hit CASCADE;
DROP TABLE IF EXISTS knowledge_chunk_index CASCADE;
DROP TABLE IF EXISTS ingest_job CASCADE;
DROP TABLE IF EXISTS ai_run_artifact CASCADE;
DROP TABLE IF EXISTS ai_guardrail_event CASCADE;
DROP TABLE IF EXISTS ai_model_run CASCADE;
DROP TABLE IF EXISTS query_result_department CASCADE;
DROP TABLE IF EXISTS query_result_follow_up_question CASCADE;
DROP TABLE IF EXISTS query_result_snapshot CASCADE;
DROP TABLE IF EXISTS query_run CASCADE;
DROP TABLE IF EXISTS ai_turn CASCADE;
DROP TABLE IF EXISTS knowledge_chunk CASCADE;
DROP TABLE IF EXISTS knowledge_release CASCADE;
DROP TABLE IF EXISTS knowledge_index_version CASCADE;
DROP TABLE IF EXISTS knowledge_document CASCADE;
DROP TABLE IF EXISTS knowledge_base CASCADE;
DROP TABLE IF EXISTS ai_session CASCADE;
DROP TABLE IF EXISTS ai_triage_result CASCADE;

DROP TABLE IF EXISTS audit.data_access_log CASCADE;
DROP TABLE IF EXISTS audit.audit_event CASCADE;

DROP TABLE IF EXISTS prescription_item CASCADE;
DROP TABLE IF EXISTS prescription_order CASCADE;
DROP TABLE IF EXISTS emr_diagnosis CASCADE;
DROP TABLE IF EXISTS emr_record CASCADE;

DROP TABLE IF EXISTS visit_encounter CASCADE;
DROP TABLE IF EXISTS registration_order CASCADE;
DROP TABLE IF EXISTS clinic_slot CASCADE;
DROP TABLE IF EXISTS clinic_session CASCADE;

DROP TABLE IF EXISTS doctor_department_rel CASCADE;
DROP TABLE IF EXISTS doctors CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS data_scope_rules CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS patient_profile CASCADE;
DROP TABLE IF EXISTS users CASCADE;
